Navigation
ViniciusAbdon09/animeflix pull request #1
Opened 2021-04-29 18:06 UTC by ViniciusAbdon09

Implementing stack navigation

2021-04-29 18:44 UTC, iuricernov requested changes
Está ok, só uma mudança (bem importante)

2021-04-29 18:44 UTC, iuricernov commented on src/Screens/Results.js
> +export default Results;
Para as telas acima, utilizar o sufixo Screen para nomear
Por exemplo, `ResultsScreen`
O motivo é que depois que o código fica maior, não dá para saber o que somente `Results` se refere - se é um objeto com resultados, se é um componente, se é a tela de fato, etc

2021-04-30 11:54 UTC, yuri-akira approved these changes
Boa!

2021-04-30 12:00 UTC, iuricernov approved these changes

2021-04-30 12:10 UTC, merged